USE cmpe451_db;

ALTER TABLE TAG
  ADD COLUMN TAG_CONTEXT VARCHAR(1024);

ALTER TABLE POST
  ADD COLUMN PLACE TEXT;

CREATE TABLE FOLLOW_HERITAGE (
	FOLLOWER_ID BIGINT NOT NULL,
	HERITAGE_ID BIGINT NOT NULL,
	PRIMARY KEY (FOLLOWER_ID, HERITAGE_ID),
	FOREIGN KEY (FOLLOWER_ID) REFERENCES MEMBER(ID),
	FOREIGN KEY (HERITAGE_ID) REFERENCES HERITAGE(ID)
);

CREATE TABLE FOLLOW_TAG (
	FOLLOWER_ID BIGINT NOT NULL,
	TAG_ID BIGINT NOT NULL,
	PRIMARY KEY (FOLLOWER_ID, TAG_ID),
	FOREIGN KEY (FOLLOWER_ID) REFERENCES MEMBER(ID),
	FOREIGN KEY (TAG_ID) REFERENCES TAG(ID)
);

ALTER TABLE MEMBER
	ADD COLUMN BIOGRAPHY TEXT;

CREATE TABLE GAMIFICATION (
  ID BIGINT NOT NULL AUTO_INCREMENT,
	USER_ID BIGINT NOT NULL,
	POST_NUM BIGINT DEFAULT 0,
	POST_LEVEL INT DEFAULT 0,
	HERITAGE_NUM BIGINT DEFAULT 0,
	HERITAGE_LEVEL INT DEFAULT 0,
	FOLLOWER_NUM BIGINT DEFAULT 0,
	FOLLOWER_LEVEL INT DEFAULT 0,
	FOLLOWEE_NUM BIGINT DEFAULT 0,
	FOLLOWEE_LEVEL INT DEFAULT 0,
	COMMENT_NUM BIGINT DEFAULT 0,
	COMMENT_LEVEL INT DEFAULT 0,
	UPVOTE_NUM BIGINT DEFAULT 0,
	UPVOTE_LEVEL INT DEFAULT 0,
	DOWNVOTE_NUM BIGINT DEFAULT 0,
	DOWNVOTE_LEVEL INT DEFAULT 0,
	OVERALL_LEVEL INT DEFAULT 0,
	PRIMARY KEY (ID),
	FOREIGN KEY (USER_ID) REFERENCES MEMBER(ID)
);

ALTER TABLE HERITAGE
	MODIFY COLUMN DESCRIPTION TEXT NOT NULL;

ALTER TABLE HERITAGE
	ADD COLUMN EVENT_DATE TIMESTAMP NULL DEFAULT NULL AFTER POST_DATE;

