USE cmpe451_db;

ALTER TABLE TAG
  ADD COLUMN TAG_CONTEXT VARCHAR(1024);

ALTER TABLE POST
  ADD COLUMN PLACE TEXT;

CREATE TABLE FOLLOW_HERITAGE (
	FOLLOWER_ID BIGINT NOT NULL,
	HERITAGE_ID BIGINT NOT NULL,
	PRIMARY KEY (FOLLOWER_ID, HERITAGE_ID),
	FOREIGN KEY (FOLLOWER_ID) REFERENCES MEMBER(ID),
	FOREIGN KEY (HERITAGE_ID) REFERENCES HERITAGE(ID)
);
