-- Table CREATE scripts --

CREATE TABLE TAG (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	TAG_TEXT VARCHAR(1024) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE MEMBER (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	USERNAME VARCHAR(64) NOT NULL UNIQUE,
	PASSWORD VARCHAR(128) NOT NULL,
	EMAIL VARCHAR(64) NOT NULL UNIQUE,
	PROFILE_PICTURE VARCHAR(256),
	PRIMARY KEY (ID)
);

CREATE TABLE POST (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	OWNER BIGINT NOT NULL,
	TYPE INT NOT NULL,
	POST_DATE TIMESTAMP NOT NULL,
	LAST_EDITED_DATE TIMESTAMP,
	TITLE VARCHAR(128),
	CONTENT TEXT NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (OWNER) REFERENCES MEMBER(ID)
);

CREATE TABLE COMMENT (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	OWNER_ID BIGINT NOT NULL,
	POST_ID BIGINT NOT NULL,
	CONTENT TEXT NOT NULL,
	POST_DATE TIMESTAMP NOT NULL,
	LAST_EDITED_DATE TIMESTAMP,
	PRIMARY KEY (ID),
	FOREIGN KEY (OWNER_ID) REFERENCES MEMBER(ID),
	FOREIGN KEY (POST_ID) REFERENCES POST(ID)
);

CREATE TABLE HERITAGE (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(64) NOT NULL,
	PLACE VARCHAR(64),
	POST_DATE TIMESTAMP NOT NULL,
	DESCRIPTION VARCHAR(1024) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE TAG_POST (
	TAG_ID BIGINT NOT NULL,
	POST_ID BIGINT NOT NULL,
	PRIMARY KEY (TAG_ID, POST_ID),
	FOREIGN KEY (TAG_ID) REFERENCES TAG(ID),
	FOREIGN KEY (POST_ID) REFERENCES POST(ID)
);

CREATE TABLE TAG_HERITAGE (
	TAG_ID BIGINT NOT NULL,
	HERITAGE_ID BIGINT NOT NULL,
	PRIMARY KEY (TAG_ID, HERITAGE_ID),
	FOREIGN KEY (TAG_ID) REFERENCES TAG(ID),
	FOREIGN KEY (HERITAGE_ID) REFERENCES HERITAGE(ID)
);

CREATE TABLE POST_VOTE (
	MEMBER_ID BIGINT NOT NULL,
	POST_ID BIGINT NOT NULL,
	VOTE_TYPE BIT(1) NOT NULL,
	PRIMARY KEY (MEMBER_ID, POST_ID),
	FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(ID),
	FOREIGN KEY (POST_ID) REFERENCES POST(ID)
);

CREATE TABLE HERITAGE_POST (
	HERITAGE_ID BIGINT NOT NULL,
	POST_ID BIGINT NOT NULL,
	PRIMARY KEY (HERITAGE_ID, POST_ID),
	FOREIGN KEY (HERITAGE_ID) REFERENCES HERITAGE(ID),
	FOREIGN KEY (POST_ID) REFERENCES POST(ID)
);

CREATE TABLE COMMENT_VOTE (
	MEMBER_ID BIGINT NOT NULL,
	COMMENT_ID BIGINT NOT NULL,
	VOTE_TYPE BIT(1) NOT NULL,
	PRIMARY KEY (MEMBER_ID, COMMENT_ID),
	FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(ID),
	FOREIGN KEY (COMMENT_ID) REFERENCES COMMENT(ID)
);

CREATE TABLE MEDIA (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	POST_OR_HERITAGE_ID BIGINT NOT NULL,
	MEDIA_LINK VARCHAR(256) NOT NULL,
	MEDIA_TYPE INT NOT NULL,
	POST_OR_HERITAGE BIT(1) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE FOLLOW (
	FOLLOWER_ID BIGINT NOT NULL,
	FOLLOWEE_ID BIGINT NOT NULL,
	PRIMARY KEY (FOLLOWER_ID, FOLLOWEE_ID),
	FOREIGN KEY (FOLLOWER_ID) REFERENCES MEMBER(ID),
	FOREIGN KEY (FOLLOWEE_ID) REFERENCES MEMBER(ID)
);

-- !!! This table is created later. You HAVE TO run the following code for the password reset feature !!! --
CREATE TABLE RESET_PASSWORD (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	MEMBER_ID BIGINT NOT NULL,
	TOKEN TEXT NOT NULL,
	REQUESTED_DATE TIMESTAMP,
	PRIMARY KEY (ID),
	FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(ID)
);


SHOW ENGINE INNODB STATUS;

